### PR TITLE
Pmm 6592 ports to pmm admin output

### PR DESCRIPTION
**Pull request by koltsov-iv**
PMM-0

Build: SUBMODULES-0

- [ ] Links to other linked pull requests (optional).

### CODE REVIEW

**Comment by ritbl** [comment]
@imil1991 how have you checked if it works?

**Comment by imil1991** [comment]
> @imil1991 how have you checked if it works?

Sorry, my bad, I've missed tests. 
It has fixed now.
Also will be great to write test for inventory/list_agents command.

**Comment by ritbl** [comment]
@imil1991 have you tested with real PMM?

**Comment by imil1991** [comment]
> @imil1991 have you tested with real PMM?

No, I didn't setup env.

**Comment by ritbl** [comment]
@imil1991 in this case, how do you know that your changes are actually working?

**Comment by imil1991** [comment]
> @imil1991 in this case, how do you know that your changes are actually working?

I can't be sure, I did this as test task, not as production task.
It can considering like draft.
If it need to be production task it will take match more time.

**Comment by ritbl** [comment]
@imil1991 sorry, but it shows your bad attitude, how can one submit even a test assignment without testing it.

**Comment by imil1991** [comment]
> @imil1991 sorry, but it shows your bad attitude, how can one submit even a test assignment without testing it.

Understand you, unfortunately didn't have match time to implement features. In my opinion it's not a very effective way to get a knowledge appraisal. I sincerely hope that you main reason is not obtaining a completed feature on the prod.
Screenshot 2022-05-04 at 10 08 09

**Pull request closed without merging**
