### PR TITLE
PMM-8308: update ref to PMM API

### PR DESCRIPTION
**Pull request by qwest812**
Related tickets: 
 - https://jira.percona.com/browse/PMM-8308

FB: https://github.com/Percona-Lab/pmm-submodules/pull/2307

Related changes:
 - pmm https://github.com/percona/pmm/pull/821
 - pmm-agent  https://github.com/percona/pmm-agent/pull/314
 - pmm-managed https://github.com/percona/pmm-managed/pull/988

### CODE REVIEW

**Review by BupycHuk — APPROVED** [review]
I'm not sure how it's related to the task mentioned in the title. But I see that `replace` in `go.mod` might be useful.

**Review by BupycHuk — CHANGES_REQUESTED** [review]
As far as I see process exec path is not shown in `pmm-admin summary`.

**Comment by qwest812** [comment]
> I'm not sure how it's related to the task mentioned in the title. But I see that `replace` in `go.mod` might be useful.


replace changes are needed, so to test Summary locally, there are no changes in the pmm package on github yet, changes are needed to work https://github.com/percona/pmm/pull/821

**Comment by qwest812** [comment]
> As far as I see process exec path is not shown in `pmm-admin summary`.

I changed dependencies

**Review by BupycHuk — APPROVED** [review]

**Review by artemgavrilov — APPROVED** [review]

**Pull request merged**
