### PR TITLE
PMM-5645 Update API and open api to use go 1.14

### PR DESCRIPTION
**Pull request by askomorokhov**
https://jira.percona.com/browse/PMM-5645

FB: https://github.com/Percona-Lab/pmm-submodules/pull/910

### CODE REVIEW

**Review by AlekSi — CHANGES_REQUESTED** [review]
Please add `1.14.x` to Travis CI config there and in other repos

**Comment by askomorokhov** [comment]
> Please add `1.14.x` to Travis CI config there and in other repos

@AlekSi, I'm doing this in the scope of another ticket https://jira.percona.com/browse/PMM-6120 .

**Comment by AlekSi** [comment]
Well, but then we don't really know if this spec change actually fixes our problem?

**Comment by AlekSi** [comment]
And that ticket you mentioned is mostly about packaging

**Comment by askomorokhov** [comment]
Well, then I'll move item about "Go version in Travis CI" from PMM-6120 to PMM-5645.

**Review by BupycHuk — APPROVED** [review]

**Review by percona-csalguero — APPROVED** [review]

**Review by JiriCtvrtka — APPROVED** [review]

**Review by artemgavrilov — APPROVED** [review]

**Pull request merged**
